version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    restart: on-failure
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
    ports:
      - "5432:5432"  
  redis:
    image: "redis:latest"
    restart: on-failure
    ports:
      - "6379:6379"